attributes:
  metadata:
    label: "Detach Keystone Plugin"
    weight: 90
    restrictions:
      - condition: "settings:additional_components.ceilometer.value == true"
        message: "Detach Keystone plugin does not support deployment with ceilometer."
      - condition: "settings:detach-database.metadata.enabled == false"
        message: "Detach Database plugin should be installed and enabled."
  yaml_additional_config:
    description: |
      NOTE: This plugin requires the Detach Database plugin, located at
      https://github.com/stackforge/fuel-plugin-detach-database
      You cannot add any Keystone role nodes without enabling the plugin.
      This field contains free form YAML to provide extra parameters.
    type: "textarea"
    weight: 52
    value: |
      #Uncomment and adjust to enable remote keystone
      #remote_keystone: 10.20.5.22
      #keystone:
      #  admin_token: REMOTE_KEYSTONE_TOKEN
    label: "Additional config"
    regex:
      source: '.+'
      error: "This field should not be empty"

