attributes:
  metadata:
    label: "Keystone settings (NOTE: Requires detach-database plugin!!!)"
    weight: 90
  yaml_additional_config:
    type: "textarea"
    weight: 52
    value: |
      #Uncomment and adjust to enable remote keystone
      #remote_keystone: 10.20.5.22
      #keystone:
      #  admin_token: REMOTE_KEYSTONE_TOKEN
    label: "Additional config"
    description: "Just put here valid yaml"
    regex:
      source: '.+'
      error: "This field should not be empty"
